package com.jfrog.xray.client.impl.test;

import com.jfrog.xray.client.impl.services.system.VersionImpl;
import com.jfrog.xray.client.services.system.Version;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;

/**
 * Created by romang on 6/6/17.
 */
public class VersionTests {

    @Test(dataProvider = "provideVersion")
    public void testBasicVersion(String verStr, String atLeast, boolean expected) {
        Version ver = new VersionImpl(verStr, "");
        boolean actual = ver.isAtLeast(atLeast);
        assertEquals(actual, expected, "Expecting " + expected + " Got: " + actual);
    }

    @DataProvider
    private Object[][] provideVersion() {

        return new Object[][]{
                // Version, AtLeast, Expected
                {"1.0.0", "0.0.0", true},
                {"1.0.0", "0.0. ", true},
                {"1.0.0", "0.0", true},
                {"1.0.0", "0.", true},
                {"1.0.0", "0", true},
                {"1.0.0", "0.1.0", true},
                {"1.0.0", "0.0.1", true},
                {"1.0.0", "0.1.1", true},
                {"1.0.0", "0.1.", true},
                {"1.0.0", "0.1", true},
                {"1.0.0", "1.0.0", true},
                {"1.0.0", "1.0", true},
                {"1.0.0", "1", true},
                {"1.0.0", "1.0.1", false},
                {"1.0.0", "1.1.0", false},
                {"1.0.0", "1.1.", false},
                {"1.0.0", "1.1", false},
                {"1.0.0", "1.1.1", false},
                {"1.0.0", "0.0.0-SNAPSHOT", true},
                {"1.0.0", "0.0.1-SNAPSHOT", true},
                {"1.0.0", "0.1.0-SNAPSHOT", true},
                {"1.0.0", "0.1.1-SNAPSHOT", true},
                {"1.0.0", "1.0.0-SNAPSHOT", false},
                {"1.0.0", "1.0.1-SNAPSHOT", false},
                {"1.0.0", "1.1.0-SNAPSHOT", false},
                {"1.0.0", "1.1.1-SNAPSHOT", false},
                {"1.0.0", "0-SNAPSHOT", true},
                {"1.0.0", "0.0.1-SNAPSHOT", true},
                {"1.0.0", "0. .1-SNAPSHOT", true},
                {"1.0.0", " .0.1-SNAPSHOT", true},
                {"1.0.0", ".0.1-SNAPSHOT", true},
                {"1.0.0", "0.1-SNAPSHOT", true},
                {"1.0.0", "0.1.1-SNAPSHOT", true},
                {"1.0.0", "1-SNAPSHOT", false},
                {"1.0.0", "1.0.1-SNAPSHOT", false},
                {"1.0.0", "1.1-SNAPSHOT", false},
                {"1.0.0", "1.1.1-SNAPSHOT", false},

                // Version, AtLeast, Expected
                {"1.0.", "0.0.0", true},
                {"1.0.", "0.0. ", true},
                {"1.0.", "0.0", true},
                {"1.0.", "0.", true},
                {"1.0.", "0", true},
                {"1.0.", "0.1.0", true},
                {"1.0.", "0.0.1", true},
                {"1.0.", "0.1.1", true},
                {"1.0.", "0.1.", true},
                {"1.0.", "0.1", true},
                {"1.0.", "1.0.0", true},
                {"1.0.", "1.0", true},
                {"1.0.", "1", true},
                {"1.0.", "1.0.1", false},
                {"1.0.", "1.1.0", false},
                {"1.0.", "1.1.", false},
                {"1.0.", "1.1", false},
                {"1.0.", "1.1.1", false},
                {"1.0.", "0.0.0-SNAPSHOT", true},
                {"1.0.", "0.0.1-SNAPSHOT", true},
                {"1.0.", "0.1.0-SNAPSHOT", true},
                {"1.0.", "0.1.1-SNAPSHOT", true},
                {"1.0.", "1.0.0-SNAPSHOT", false},
                {"1.0.", "1.0.1-SNAPSHOT", false},
                {"1.0.", "1.1.0-SNAPSHOT", false},
                {"1.0.", "1.1.1-SNAPSHOT", false},
                {"1.0.", "0-SNAPSHOT", true},
                {"1.0.", "0.0.1-SNAPSHOT", true},
                {"1.0.", "0. .1-SNAPSHOT", true},
                {"1.0.", " .0.1-SNAPSHOT", true},
                {"1.0.", ".0.1-SNAPSHOT", true},
                {"1.0.", "0.1-SNAPSHOT", true},
                {"1.0.", "0.1.1-SNAPSHOT", true},
                {"1.0.", "1-SNAPSHOT", false},
                {"1.0.", "1.0.1-SNAPSHOT", false},
                {"1.0.", "1.1-SNAPSHOT", false},
                {"1.0.", "1.1.1-SNAPSHOT", false},

                // Version, AtLeast, Expected
                {"1.0", "0.0.0", true},
                {"1.0", "0.0. ", true},
                {"1.0", "0.0", true},
                {"1.0", "0.", true},
                {"1.0", "0", true},
                {"1.0", "0.1.0", true},
                {"1.0", "0.0.1", true},
                {"1.0", "0.1.1", true},
                {"1.0", "0.1.", true},
                {"1.0", "0.1", true},
                {"1.0", "1.0.0", true},
                {"1.0", "1.0", true},
                {"1.0", "1", true},
                {"1.0", "1.0.1", false},
                {"1.0", "1.1.0", false},
                {"1.0", "1.1.", false},
                {"1.0", "1.1", false},
                {"1.0", "1.1.1", false},
                {"1.0", "0.0.0-SNAPSHOT", true},
                {"1.0", "0.0.1-SNAPSHOT", true},
                {"1.0", "0.1.0-SNAPSHOT", true},
                {"1.0", "0.1.1-SNAPSHOT", true},
                {"1.0", "1.0.0-SNAPSHOT", false},
                {"1.0", "1.0.1-SNAPSHOT", false},
                {"1.0", "1.1.0-SNAPSHOT", false},
                {"1.0", "1.1.1-SNAPSHOT", false},
                {"1.0", "0-SNAPSHOT", true},
                {"1.0", "0.0.1-SNAPSHOT", true},
                {"1.0", "0. .1-SNAPSHOT", true},
                {"1.0", " .0.1-SNAPSHOT", true},
                {"1.0", ".0.1-SNAPSHOT", true},
                {"1.0", "0.1-SNAPSHOT", true},
                {"1.0", "0.1.1-SNAPSHOT", true},
                {"1.0", "1-SNAPSHOT", false},
                {"1.0", "1.0.1-SNAPSHOT", false},
                {"1.0", "1.1-SNAPSHOT", false},
                {"1.0", "1.1.1-SNAPSHOT", false},

                // Version, AtLeast, Expected
                {"1.", "0.0.0", true},
                {"1.", "0.0. ", true},
                {"1.", "0.0", true},
                {"1.", "0.", true},
                {"1.", "0", true},
                {"1.", "0.1.0", true},
                {"1.", "0.0.1", true},
                {"1.", "0.1.1", true},
                {"1.", "0.1.", true},
                {"1.", "0.1", true},
                {"1.", "1.0.0", true},
                {"1.", "1.0", true},
                {"1.", "1", true},
                {"1.", "1.0.1", false},
                {"1.", "1.1.0", false},
                {"1.", "1.1.", false},
                {"1.", "1.1", false},
                {"1.", "1.1.1", false},
                {"1.", "0.0.0-SNAPSHOT", true},
                {"1.", "0.0.1-SNAPSHOT", true},
                {"1.", "0.1.0-SNAPSHOT", true},
                {"1.", "0.1.1-SNAPSHOT", true},
                {"1.", "1.0.0-SNAPSHOT", false},
                {"1.", "1.0.1-SNAPSHOT", false},
                {"1.", "1.1.0-SNAPSHOT", false},
                {"1.", "1.1.1-SNAPSHOT", false},
                {"1.", "0-SNAPSHOT", true},
                {"1.", "0.0.1-SNAPSHOT", true},
                {"1.", "0. .1-SNAPSHOT", true},
                {"1.", " .0.1-SNAPSHOT", true},
                {"1.", ".0.1-SNAPSHOT", true},
                {"1.", "0.1-SNAPSHOT", true},
                {"1.", "0.1.1-SNAPSHOT", true},
                {"1.", "1-SNAPSHOT", false},
                {"1.", "1.0.1-SNAPSHOT", false},
                {"1.", "1.1-SNAPSHOT", false},
                {"1.", "1.1.1-SNAPSHOT", false},

                // Version, AtLeast, Expected
                {"1", "0.0.0", true},
                {"1", "0.0. ", true},
                {"1", "0.0", true},
                {"1", "0.", true},
                {"1", "0", true},
                {"1", "0.1.0", true},
                {"1", "0.0.1", true},
                {"1", "0.1.1", true},
                {"1", "0.1.", true},
                {"1", "0.1", true},
                {"1", "1.0.0", true},
                {"1", "1.0", true},
                {"1", "1", true},
                {"1", "1.0.1", false},
                {"1", "1.1.0", false},
                {"1", "1.1.", false},
                {"1", "1.1", false},
                {"1", "1.1.1", false},
                {"1", "0.0.0-SNAPSHOT", true},
                {"1", "0.0.1-SNAPSHOT", true},
                {"1", "0.1.0-SNAPSHOT", true},
                {"1", "0.1.1-SNAPSHOT", true},
                {"1", "1.0.0-SNAPSHOT", false},
                {"1", "1.0.1-SNAPSHOT", false},
                {"1", "1.1.0-SNAPSHOT", false},
                {"1", "1.1.1-SNAPSHOT", false},
                {"1", "0-SNAPSHOT", true},
                {"1", "0.0.1-SNAPSHOT", true},
                {"1", "0. .1-SNAPSHOT", true},
                {"1", " .0.1-SNAPSHOT", true},
                {"1", ".0.1-SNAPSHOT", true},
                {"1", "0.1-SNAPSHOT", true},
                {"1", "0.1.1-SNAPSHOT", true},
                {"1", "1-SNAPSHOT", false},
                {"1", "1.0.1-SNAPSHOT", false},
                {"1", "1.1-SNAPSHOT", false},
                {"1", "1.1.1-SNAPSHOT", false},

                // Version, AtLeast, Expected
                {"1.0.0-SNAPSHOT", "0.0.0", true},
                {"1.0.0-SNAPSHOT", "0.1.0", true},
                {"1.0.0-SNAPSHOT", "0.0.1", true},
                {"1.0.0-SNAPSHOT", "0.1.1", true},
                {"1.0.0-SNAPSHOT", "1.0.0", true},
                {"1.0.0-SNAPSHOT", "1.0.1", false},
                {"1.0.0-SNAPSHOT", "1.1.0", false},
                {"1.0.0-SNAPSHOT", "1.1.1", false},
                {"1.0.0-SNAPSHOT", "0.0.0-SNAPSHOT", true},
                {"1.0.0-SNAPSHOT", "0.0.1-SNAPSHOT", true},
                {"1.0.0-SNAPSHOT", "0.1.0-SNAPSHOT", true},
                {"1.0.0-SNAPSHOT", "0.1.1-SNAPSHOT", true},
                {"1.0.0-SNAPSHOT", "1.0.0-SNAPSHOT", true},
                {"1.0.0-SNAPSHOT", "1.0.1-SNAPSHOT", false},
                {"1.0.0-SNAPSHOT", "1.1.0-SNAPSHOT", false},
                {"1.0.0-SNAPSHOT", "1.1.1-SNAPSHOT", false},

                // Version, AtLeast, Expected
                {"1.0.0-A", "0.0.0", true},
                {"1.0.0-A", "0.1.0", true},
                {"1.0.0-A", "0.0.1", true},
                {"1.0.0-A", "0.1.1", true},
                {"1.0.0-A", "1.0.0", true},
                {"1.0.0-A", "1.0.1", false},
                {"1.0.0-A", "1.1.0", false},
                {"1.0.0-A", "1.1.1", false},
                {"1.0.0-A", "0.0.0-B", true},
                {"1.0.0-A", "0.0.1-B", true},
                {"1.0.0-A", "0.1.0-B", true},
                {"1.0.0-A", "0.1.1-B", true},
                {"1.0.0-A", "1.0.0-B", false},
                {"1.0.0-A", "1.0.1-B", false},
                {"1.0.0-A", "1.1.0-B", false},
                {"1.0.0-A", "1.1.1-B", false},

                // Version, AtLeast, Expected
                {"1.0.0-B", "0.0.0-A", true},
                {"1.0.0-B", "0.0.1-A", true},
                {"1.0.0-B", "0.1.0-A", true},
                {"1.0.0-B", "0.1.1-A", true},
                {"1.0.0-B", "1.0.0-A", true},
                {"1.0.0-B", "1.0.1-A", false},
                {"1.0.0-B", "1.1.0-A", false},
                {"1.0.0-B", "1.1.1-A", false},

                // Version, AtLeast, Expected
                {"12.0.0", "0.0.0", true},
                {"12.0.0", "0.0.2", true},
                {"12.0.0", "0.2.0", true},
                {"12.0.0", "0.2.3", true},
                {"12.0.0", "2.0.0", true},
                {"12.0.0", "2.0.3", true},
                {"12.0.0", "2.3.0", true},
                {"12.0.0", "2.3.4", true},
                {"12.0.0", "0.0.12", true},
                {"12.0.0", "0.22.0", true},
                {"12.0.0", "0.23.34", true},
                {"12.0.0", "2.34.45", true},
                {"12.0.0", "23.0.0", false},
                {"12.0.0", "23.0.34", false},
                {"12.0.0", "23.34.0", false},
                {"12.0.0", "0.0.0-SNAPSHOT", true},
                {"12.0.0", "0.0.2-SNAPSHOT", true},
                {"12.0.0", "0.2.0-SNAPSHOT", true},
                {"12.0.0", "0.2.3-SNAPSHOT", true},
                {"12.0.0", "2.0.0-SNAPSHOT", true},
                {"12.0.0", "2.0.3-SNAPSHOT", true},
                {"12.0.0", "2.3.0-SNAPSHOT", true},
                {"12.0.0", "2.3.4-SNAPSHOT", true},
                {"12.0.0", "12.0.0-SNAPSHOT", false},
                {"2.0.0-m003", "1.7.2.3", true}
        };
    }
}
