pipelines:
  - name: release_jfrog_idea_plugin
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "17"
      environmentVariables:
        readOnly:
          NEXT_VERSION: 0.0.0
          NEXT_DEVELOPMENT_VERSION: 0.0.x-SNAPSHOT
          SKIP_AUDIT: "false"

    steps:
      - name: Release
        type: Bash
        configuration:
          inputResources:
            - name: jfrogIdeaPluginReleaseGit
          integrations:
            - name: il_automation
            - name: ecosys_entplus_deployer
            - name: jetbrains
        execution:
          onExecute:
            - cd $res_jfrogIdeaPluginReleaseGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_BUILD_STATUS=PASS
            - export JFROG_CLI_BUILD_NAME=ecosystem-jfrog-idea-plugin-release
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            - export JFROG_CLI_BUILD_PROJECT=ecosys

            # Configure git
            - if [[ $NEXT_VERSION =~ ^1.* ]]; then BRANCH="v1"; else BRANCH="master"; fi
            - git checkout ${BRANCH}
            - git remote set-url origin https://$int_il_automation_token@github.com/jfrog/jfrog-idea-plugin.git

            # Make sure versions provided
            - echo "Checking variables"
            - test -n "$NEXT_VERSION" -a "$NEXT_VERSION" != "0.0.0"
            - test -n "$NEXT_DEVELOPMENT_VERSION" -a "$NEXT_DEVELOPMENT_VERSION" != "0.0.x-SNAPSHOT"

            # Configure JFrog CLI
            - curl -fL https://install-cli.jfrog.io | sh
            - jf c rm --quiet
            - jf c add internal --url=$int_ecosys_entplus_deployer_url --user=$int_ecosys_entplus_deployer_user --password=$int_ecosys_entplus_deployer_apikey

            # Run audit
            - |
              if [ "$SKIP_AUDIT" != "true" ]; then
                jf audit
              else
                echo "Skipping audit according to environment variable"
              fi

            # Update version
            - sed -i "s/\(currentVersion=\).*\$/\1${NEXT_VERSION}/" gradle.properties
            - git commit -am "[artifactory-release] Release version ${NEXT_VERSION} [skipRun]" --allow-empty
            - git tag ${NEXT_VERSION}

            # Run build and publish
            - jf gradlec --use-wrapper --repo-deploy ecosys-oss-release-local --deploy-maven-desc --deploy-ivy-desc=false
            - >
              env -i PATH=$PATH HOME=$HOME CI=$CI
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              JFROG_CLI_BUILD_PROJECT=$JFROG_CLI_BUILD_PROJECT
              jf gradle clean buildPlugin -x test artifactoryPublish
            - jf rt bag && jf rt bce
            - jf rt bp

            # Distribute release bundle
            - jf ds rbc ecosystem-jfrog-idea-plugin $NEXT_VERSION --spec=./release/specs/prod-rbc-filespec.json --spec-vars="version=$NEXT_VERSION" --sign
            - jf ds rbd ecosystem-jfrog-idea-plugin $NEXT_VERSION --site="releases.jfrog.io" --sync

            # Upload to Jetbrains marketplace
            - env -i PATH=$PATH HOME=$HOME JAVA_HOME=$JAVA_HOME JETBRAINS_TOKEN=$int_jetbrains_token ./gradlew publishPlugin

            # Update next development version
            - sed -i "s/\(currentVersion=\).*\$/\1${NEXT_DEVELOPMENT_VERSION}/" gradle.properties
            - git commit -am "[jfrog-release] Next development version [skipRun]"
            - git push
            - git push --tags
