updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status ideaReleaseGit --context "$step_name"

pipelines:
  - name: build_idea
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "11"
      environmentVariables:
        readOnly:
          NEXT_VERSION: 0.0.0
          NEXT_DEVELOPMENT_VERSION: 0.0.x-SNAPSHOT

    steps:
      - name: Release
        type: Bash
        configuration:
          inputResources:
            - name: ideaReleaseGit
          integrations:
            - name: ojo
            - name: github_generic
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files gradle_cache $res_ideaReleaseGit_resourcePath/.gradle
          onExecute:
            - cd $res_ideaReleaseGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_CLI_BUILD_NAME=jfrog-idea-plugin
            - export JFROG_CLI_BUILD_NUMBER=$run_number

            # Configure git
            - git checkout master
            - git remote set-url origin https://$int_github_generic_token@github.com/jfrog/jfrog-idea-plugin.git

            # Make sure versions provided
            - echo "Checking variables"
            - test -n "$NEXT_VERSION" -a "$NEXT_VERSION" != "0.0.0"
            - test -n "$NEXT_DEVELOPMENT_VERSION" -a "$NEXT_DEVELOPMENT_VERSION" != "0.0.x-SNAPSHOT"

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Configure JFrog CLI
            - ./jfrog c add ojo --artifactory-url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt gradlec --use-wrapper --deploy-ivy-desc=false --deploy-maven-desc=false
              --server-id-resolve ojo --repo-resolve remote-repos
              --server-id-deploy ojo --repo-deploy oss-release-local

            # Update version
            - sed -i "s/\(currentVersion=\).*\$/\1${NEXT_VERSION}/" gradle.properties
            - git commit -am "[artifactory-release] Release version ${NEXT_VERSION} [skipRun]" --allow-empty
            - git tag ${NEXT_VERSION}
            - git push
            - git push --tags

            # Run build and publish
            - >
              env -i PATH=$PATH HOME=$HOME GRADLE_OPTS=-Dorg.gradle.daemon=false
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              ./jfrog rt gradle clean verifyPlugin buildPlugin artifactoryPublish
            - ./jfrog rt bp

            # Update next development version
            - sed -i "s/\(currentVersion=\).*\$/\1${NEXT_DEVELOPMENT_VERSION}/" gradle.properties
            - git commit -am "[artifactory-release] Next development version [skipRun]"
            - git push

          onComplete:
            - *UPDATE_COMMIT_STATUS

            # Save .m2 cache
            - add_cache_files $res_ideaReleaseGit_resourcePath/.gradle gradle_cache