name: IntegrationTests

on:
  schedule:
    - cron: '* 8 * * *' # Runs every day at 8:00 AM

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        include:
          - os: windows-latest
            gradle_suffix: .bat
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Install required tools
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 5.6.4

      # Run tests
      - name: Tests on macOS, Linux
        env:
          JFROG_IDE_PLATFORM_URL: ${{ secrets.PLATFORM_URL }}
          JFROG_IDE_ACCESS_TOKEN: ${{ secrets.PLATFORM_ADMIN_TOKEN }}

        run: ./gradlew${{ gradle_suffix }} clean integrationTests
